; Script generated by Antigravity for SnapFind Setup

#ifndef AppVersion
#define AppVersion "1.0.0"
#endif

[Setup]
AppName=SnapFind
AppVersion={#AppVersion}
AppPublisher=SnapFind Developer
DefaultDirName={localappdata}\SnapFind
DefaultGroupName=SnapFind
DisableProgramGroupPage=yes
DisableDirPage=no
UsePreviousAppDir=yes
UsePreviousTasks=yes
CloseApplications=yes
PrivilegesRequired=lowest
OutputBaseFilename=SnapFindSetup_v{#AppVersion}
Compression=lzma2/ultra
SolidCompression=yes
AppMutex=SnapFind-SingleInstance-Mutex-Key
WizardStyle=modern
UninstallDisplayIcon={app}\SnapFind.exe
OutputDir=e:\SnapFind\releases\installers

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "startup"; Description: "开机自启动 SnapFind"; GroupDescription: "其他任务"

[Files]
Source: "e:\SnapFind\src\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish\SnapFind.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "e:\SnapFind\libs\*"; DestDir: "{app}\libs"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\SnapFind"; Filename: "{app}\SnapFind.exe"; WorkingDir: "{app}"
Name: "{autodesktop}\SnapFind"; Filename: "{app}\SnapFind.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "SnapFind"; ValueData: """{app}\SnapFind.exe"""; Tasks: startup; Flags: uninsdeletevalue

[Run]
Filename: "{app}\SnapFind.exe"; Description: "{cm:LaunchProgram,SnapFind}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\SnapFind.exe"; Flags: nowait; Check: IsSilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}\cache"

[Code]
function IsSilent: Boolean;
begin
  Result := WizardSilent;
end;
